package item.crate

import item.crate.CrateItem.*

enum class CrateLootPool(val possibleItems: List<CrateItem>) {
    MASTER(CrateItem.entries),
    PLUSHIE(listOf(
        PENGUIN,
        MUSHROOM,
        BEE,
        STAR,
        HEART,
        RAMEN_BOWL,
        COFFEE_CUP,
        AXOLOTL_WILD,
        AXOLOTL_LUCY,
        AXOLOTL_GOLD,
        AXOLOTL_CYAN,
        AXOLOTL_BLUE,
    )),
    BABY(CrateItem.entries.filter { it.name.endsWith("BABY") }),
    WEARABLES(listOf(
        CAT_EARS,
        DOG_EARS,
        FOX_EARS,
        COOL_GLASSES,
        HALO,
        HEART_CROWN,
        ORCHID_CROWN,
        KING_CROWN,
        HEART_GLASSES,
        STRAWHAT,
        COPPER_ANTENNAS,
        COPPER_ANTENNAS_EXPOSED,
        COPPER_ANTENNAS_WEATHERED,
        COPPER_ANTENNAS_OXIDIZED,
    )),
    PLAYER(listOf(
        SEBIANN,
        COOKIE,
        BEAUVER,
        CARSON,
        LESHY,
        MAI,
        MEGAN,
        RIVEN,
        SABINE,
        YANN,
        ROAST,
        TURTLE,
        FIDEOX,
        COMTRA,
        JMO,
        LUKE,
        WHISPER,
        YAMS,
        SOHCAHTO,
        SEBIANN_CLASSIC,
        CARSON_GRAY,
        ROAST_MAID,
        SABINE_CHEER_COOL,
        COOKIE_ONYX,
    )),
    CHARACTER(listOf(
        N,
        ASTARION,
        BATMAN,
        DAZAI,
        LEVI,
        SPARROW,
        SPIDERMAN,
        LEONARDO,
        RAPHAEL,
        MICHELANGELO,
        DONATELLO,
        ROBOT,
        DARTH_VADER,
        STORMTROOPER,
        BOBA_FETT,
    )),
    SABINE_LOOTPOOL(CrateItem.entries.filter { it.name.startsWith("SABINE") }),
    COOKIE_LOOTPOOL(CrateItem.entries.filter { it.name.startsWith("COOKIE") }),
}